### ISSUE TITLE
MinimigCore: Load Configuration doesn't work anymore

### ISSUE THREAD

**Issue by sblendorio** [mist-devel/mist-binaries#24]
With this firmware (firmware_160619), while using minimigAga, and I change configuration through "Load Configuration" option, the kickstart is loaded but:

- Hard Disks are not detected
- F12 (and other ways to show OSD menu) does not work anymore

minimigAga specific version used:
http://meditation.somuch.guru/minimig/files/mist/dev/minimig_mist-20160224.zip

**Comment by sblendorio** [comment]
*updated, specified firmware_160619

**Comment by Newsdee** [comment]
Hi,

I'll have a look when I can. Does it work if you revert to the previous
firmware?

**Comment by sblendorio** [comment]
Yes, reverting to the previous firmware it all works as before.

**Comment by Newsdee** [comment]
OK, I can replicate the problem. The last good firmware is 160610.

I'll go through changes in 160613 to see what caused this. It looks like
even saving a new config and loading it back does not work; although the
original (startup) config is still working fine.

Yes, reverting to the previous firmware it all works as before.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mist-devel/mist-binaries/issues/24#issuecomment-228330343>,
or mute the thread
<https://github.com/notifications/unsubscribe/ALUtAYdTuIK1SUEljKwxk3VLHZLmbkyLks5qO8nqgaJpZM4I9hUu>
.

**Comment by sorgelig** [comment]
@Newsdee 
did you fix this problem? I'm holding ZX core release because it requires FW update, so i think, it would be good to wait this bug get fixed.

**Comment by Newsdee** [comment]
I'm working on it now. I'm not sure if it is my code or a bug in the core,
but I'm reworking all my latest changes to avoid the problem.

Will release a core disabling some features and fixing the Amiga load
config sometime today.

**Comment by Newsdee** [comment]
Load Config is now fixed.

Turbo function for button has been disabled for now - will add it back
later on.

**Comment by sblendorio** [comment]
Thank you!
P.S. I published a review about MiST, hope you'll like it!
http://www.retroacademy.it/2016/06/28/news-eng/mist-y-amiga/2649/
