### ISSUE TITLE
Vic 20 games doesn't start or crashes after last firmware upgrade

### ISSUE THREAD

**Issue by lroby74** [mist-devel/mist-binaries#34]
Hello,
after last firmware upgrade (actually version ATH160910) some Vic20 expanded games doesn't works anymore (my VIC configuration is always 32kb).

A pair of titles are "Critters.prg" and "popeye.prg" (2015 version), both works perfectly on Winvice emulator on my pc.

something is wrong on last firmware about compatibility of games with Vic 20 core?

(I have 2 different Mist, one on SCART and other one with VGA monitor, it's same thing on both units)

Thank you very much
Roberto

**Comment by harbaum** [comment]
These games were working before the firmware upgrade? Which firmware did you use before?

**Comment by lroby74** [comment]
Yes, i played to them with previous firmware, i don't remember exact
version of previous firmware but was last one before this one

2016-11-14 9:03 GMT+01:00 Till Harbaum <notifications@github.com>:

**Comment by juri74** [comment]
lroby74 gave me the two files and i tested them with follow firmwares:
160910 = not working
160721 = not working
160626 = not working
one may 2016 release = not working (sorry do not remember what may version i used :P )
160123 = not working
unfortunately i've not time to test ALL firmware releases, i'm not fpga language expert but i suspect the problem is in the vic20 core not the firmware...
maybe some really talented could have a look at the Vic20 core... latest one is TWO years old O_O

**Comment by harbaum** [comment]
So one of you is sure that it's a firmware change that broke the vic20 but doesn't know which exact version does work. And the other one claimed it never worked at all.

That'll be hard to debug :-)

Anyway, i'll see what i can do.

**Comment by lroby74** [comment]
Honestly i tried Critters only one time and that time has worked (but it
may be only luck)...

from second time it never worked anymore..

i think that Juri74 with his many tried has lighted situation.. problem is
bugged and very old Vic20 core :(

2016-11-14 11:35 GMT+01:00 Till Harbaum <notifications@github.com>:

**Comment by harbaum** [comment]
The FPGA world is small. Much smaller than e.g  PC emulator world. Thus there are also way less FPGA developers. As a result some things happen slower in FPGA world. But things are getting better with every new MIST owner.

Is there something that the non/bad-working games have in common?

**Comment by harbaum** [comment]
I doubt the firmware version has anything to do with this. The firmware has very little impact on the target machine.

**Comment by lroby74** [comment]
That i know, a common thing is that both games requires more ram (8K for
Critters and 32kb for Popeye)



2016-11-14 12:28 GMT+01:00 Till Harbaum <notifications@github.com>:

**Comment by lroby74** [comment]
At this point i think same thing , firmware is not problem.. .core is...
bugged

2016-11-14 12:30 GMT+01:00 Till Harbaum <notifications@github.com>:

**Comment by harbaum** [comment]
It's not necessarily "bugged". Often it's that a machines hardware has some undocumented side effects then doing things in an unusual way. E.g. on many machines identical portions of ram and rom show up on different places. This is called mirroring and happens when the HW developer tries to save a few gates here and there. And if some software relies on this behaviour then ... boom ...

As i said, i'll have a look.

**Comment by lroby74** [comment]
Thank you for you help

**Comment by lroby74** [comment]
Hello everybody, some news ? :(

**Comment by harbaum** [comment]
I was a little busy the last time. I hope to find some time for this, soon.

**Comment by lroby74** [comment]
Don't worry and thank you :)

2016-12-12 15:00 GMT+01:00 Till Harbaum <notifications@github.com>:

**Comment by lroby74** [comment]
Hello again, sometimes i write here hopefully of good news about Vic 20 core :)

**Comment by harbaum** [comment]
The vic20 has vastly been improved and many, many games and even demos now run.
